-- From the following tables write a SQL query to calculate the total order amount generated by a salesperson. Salespersons should be from the cities where the customers reside. Return salesperson name, city and total order amount.

SELECT s.name,
       s.city,
       o_summary.total_amt
FROM salesman s
JOIN (
    SELECT salesman_id, SUM(purch_amt) AS total_amt
    FROM orders
    GROUP BY salesman_id
) o_summary ON s.salesman_id = o_summary.salesman_id
WHERE s.city IN (SELECT DISTINCT city FROM customer);
